# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Aeolus Notebooks
author: "EOX et al."
logo: ""
only_build_toc_files: true

execute:
  execute_notebooks: cache
  run_in_temp: true

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://vre.aeolus.services"
  binderhub_url             : ""

repository:
  url: https://github.com/ESA-VirES/Aeolus-notebooks
  branch: main

html:
  use_issues_button         : true
  use_repository_button     : true
  use_edit_page_button      : false
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  home_page_in_navbar       : true
  comments:
    hypothesis              : true

# See https://jupyterbook.org/content/content-blocks.html
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
